### ISSUE TITLE
另一个会让 spmjs.io 挂的包

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spmjs.io#97]
alice-animate

**Comment by sorrycc** [comment]
有少量的 html，https://raw.githubusercontent.com/aliceui/animate/master/README.md

**Comment by sorrycc** [comment]
周末挂了不少次，我把 alice-animate 临时先 unpublish 了。

**Comment by afc163** [comment]
我一会排查一下。。。

**Comment by afc163** [comment]
```css
#yourElement {
    -vendor-animation-duration: 3s;
    -vendor-animation-delay: 2s;
    -vendor-animation-iteration-count: infinite;
}
```

对上面这个代码块高亮时，由于没有传类型，hightlight.js 进行轮询测试时报错了。
